import { type Service } from './types';

export const EMERGENCY_PHONE = '0788772489';

export const SERVICES: Service[] = [
  {
    id: 'psychoeducation',
    nameKey: 'psychoeducation',
    questions: [
      { id: 1, textKey: 'psychoeducation_q1' },
      { id: 2, textKey: 'psychoeducation_q2' },
      { id: 3, textKey: 'psychoeducation_q3' },
      { id: 4, textKey: 'psychoeducation_q4' },
      { id: 5, textKey: 'psychoeducation_q5' },
      { id: 6, textKey: 'psychoeducation_q6' },
      { id: 7, textKey: 'psychoeducation_q7' },
      { id: 8, textKey: 'psychoeducation_q8' },
      { id: 9, textKey: 'psychoeducation_q9' },
      { id: 10, textKey: 'psychoeducation_q10' },
    ],
  },
  {
    id: 'counseling',
    nameKey: 'counseling',
    questions: [
      { id: 1, textKey: 'counseling_q1' },
      { id: 2, textKey: 'counseling_q2' },
      { id: 3, textKey: 'counseling_q3' },
      { id: 4, textKey: 'counseling_q4' },
      { id: 5, textKey: 'counseling_q5' },
      { id: 6, textKey: 'counseling_q6' },
      { id: 7, textKey: 'counseling_q7' },
      { id: 8, textKey: 'counseling_q8' },
      { id: 9, textKey: 'counseling_q9' },
      { id: 10, textKey: 'counseling_q10' },
    ],
  },
  {
    id: 'addiction',
    nameKey: 'addiction',
    addictionTypes: {
      alcohol: {
        nameKey: 'addiction_alcohol',
        questions: [
          { id: 1, textKey: 'addiction_alcohol_q1' },
          { id: 2, textKey: 'addiction_alcohol_q2' },
          { id: 3, textKey: 'addiction_alcohol_q3' },
          { id: 4, textKey: 'addiction_alcohol_q4' },
          { id: 5, textKey: 'addiction_alcohol_q5' },
          { id: 6, textKey: 'addiction_alcohol_q6' },
          { id: 7, textKey: 'addiction_alcohol_q7' },
          { id: 8, textKey: 'addiction_alcohol_q8' },
          { id: 9, textKey: 'addiction_alcohol_q9' },
          { id: 10, textKey: 'addiction_alcohol_q10' },
        ],
      },
      smoking: {
        nameKey: 'addiction_smoking',
        questions: [
          { id: 1, textKey: 'addiction_smoking_q1' },
          { id: 2, textKey: 'addiction_smoking_q2' },
          { id: 3, textKey: 'addiction_smoking_q3' },
          { id: 4, textKey: 'addiction_smoking_q4' },
          { id: 5, textKey: 'addiction_smoking_q5' },
          { id: 6, textKey: 'addiction_smoking_q6' },
          { id: 7, textKey: 'addiction_smoking_q7' },
          { id: 8, textKey: 'addiction_smoking_q8' },
          { id: 9, textKey: 'addiction_smoking_q9' },
          { id: 10, textKey: 'addiction_smoking_q10' },
        ],
      },
      injection: {
        nameKey: 'addiction_injection',
        questions: [
          { id: 1, textKey: 'addiction_injection_q1' },
          { id: 2, textKey: 'addiction_injection_q2' },
          { id: 3, textKey: 'addiction_injection_q3' },
          { id: 4, textKey: 'addiction_injection_q4' },
          { id: 5, textKey: 'addiction_injection_q5' },
          { id: 6, textKey: 'addiction_injection_q6' },
          { id: 7, textKey: 'addiction_injection_q7' },
          { id: 8, textKey: 'addiction_injection_q8' },
          { id: 9, textKey: 'addiction_injection_q9' },
          { id: 10, textKey: 'addiction_injection_q10' },
        ],
      },
    },
  },
  {
    id: 'art_therapy',
    nameKey: 'art_therapy',
    questions: [
      { id: 1, textKey: 'art_therapy_q1' },
      { id: 2, textKey: 'art_therapy_q2' },
      { id: 3, textKey: 'art_therapy_q3' },
      { id: 4, textKey: 'art_therapy_q4' },
      { id: 5, textKey: 'art_therapy_q5' },
      { id: 6, textKey: 'art_therapy_q6' },
      { id: 7, textKey: 'art_therapy_q7' },
      { id: 8, textKey: 'art_therapy_q8' },
      { id: 9, textKey: 'art_therapy_q9' },
      { id: 10, textKey: 'art_therapy_q10' },
    ],
  },
  {
    id: 'relaxation',
    nameKey: 'relaxation',
    questions: [
      { id: 1, textKey: 'relaxation_q1' },
      { id: 2, textKey: 'relaxation_q2' },
      { id: 3, textKey: 'relaxation_q3' },
      { id: 4, textKey: 'relaxation_q4' },
      { id: 5, textKey: 'relaxation_q5' },
      { id: 6, textKey: 'relaxation_q6' },
      { id: 7, textKey: 'relaxation_q7' },
      { id: 8, textKey: 'relaxation_q8' },
      { id: 9, textKey: 'relaxation_q9' },
      { id: 10, textKey: 'relaxation_q10' },
    ],
  },
  {
    id: 'ergo_therapy',
    nameKey: 'ergo_therapy',
    questions: [
      { id: 1, textKey: 'ergo_therapy_q1' },
      { id: 2, textKey: 'ergo_therapy_q2' },
      { id: 3, textKey: 'ergo_therapy_q3' },
      { id: 4, textKey: 'ergo_therapy_q4' },
      { id: 5, textKey: 'ergo_therapy_q5' },
      { id: 6, textKey: 'ergo_therapy_q6' },
      { id: 7, textKey: 'ergo_therapy_q7' },
      { id: 8, textKey: 'ergo_therapy_q8' },
      { id: 9, textKey: 'ergo_therapy_q9' },
      { id: 10, textKey: 'ergo_therapy_q10' },
    ],
  },
  {
    id: 'psychosocial_support',
    nameKey: 'psychosocial_support',
    questions: [
      { id: 1, textKey: 'psychosocial_support_q1' },
      { id: 2, textKey: 'psychosocial_support_q2' },
      { id: 3, textKey: 'psychosocial_support_q3' },
      { id: 4, textKey: 'psychosocial_support_q4' },
      { id: 5, textKey: 'psychosocial_support_q5' },
      { id: 6, textKey: 'psychosocial_support_q6' },
      { id: 7, textKey: 'psychosocial_support_q7' },
      { id: 8, textKey: 'psychosocial_support_q8' },
      { id: 9, textKey: 'psychosocial_support_q9' },
      { id: 10, textKey: 'psychosocial_support_q10' },
    ],
  },
];